grpc_client_node:
  ros__parameters:
    server_url: "172.30.32.224"
    server_port: 32051
    robot_id: "test_robot_1"
    robot_secret: "abcdzxcv"
    request_expired: 3.0
    server_ip: "172.30.32.224"
